# Generated by Django 2.0.6 on 2018-12-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demobaza', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='включён')),
                ('verified', models.DateTimeField(null=True, verbose_name='проверен администрацией')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='название')),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('short_text', models.TextField(blank=True, verbose_name='короткий текст')),
                ('long_text', models.TextField(blank=True, verbose_name='длинный текст')),
            ],
            options={
                'verbose_name': 'музыкант',
                'verbose_name_plural': 'музыканты',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
        migrations.AddField(
            model_name='user',
            name='musicians',
            field=models.ManyToManyField(related_name='users', to='demobaza.Musician', verbose_name='музыканты'),
        ),
    ]
