# Generated by Django 2.1.4 on 2018-12-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demobaza', '0002_auto_20181225_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='название')),
                ('slug', models.SlugField(editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'жанр',
                'verbose_name_plural': 'жанры',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='musician',
            options={'ordering': ('name',), 'verbose_name': 'музыкант', 'verbose_name_plural': 'музыканты'},
        ),
        migrations.AlterField(
            model_name='user',
            name='musicians',
            field=models.ManyToManyField(blank=True, related_name='users', to='demobaza.Musician', verbose_name='музыканты'),
        ),
        migrations.AddField(
            model_name='musician',
            name='genres',
            field=models.ManyToManyField(blank=True, to='demobaza.Genre', verbose_name='жанры'),
        ),
    ]
