# Generated by Django 2.1.4 on 2018-12-25 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demobaza', '0004_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='city_musicians', to='demobaza.Genre', verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='genre_musicians', to='demobaza.Genre', verbose_name='жанры'),
        ),
    ]
