# Generated by Django 2.1.4 on 2018-12-25 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demobaza', '0005_auto_20181225_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='название')),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('short_text', models.TextField(blank=True, verbose_name='короткий текст')),
                ('long_text', models.TextField(blank=True, verbose_name='длинный текст')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='festivals', to='demobaza.City', verbose_name='город')),
            ],
            options={
                'verbose_name': 'фестиваль',
                'verbose_name_plural': 'фестивали',
                'ordering': ('name',),
            },
        ),
        migrations.RemoveField(
            model_name='musician',
            name='enabled',
        ),
        migrations.AddField(
            model_name='musician',
            name='archive',
            field=models.BooleanField(default=False, verbose_name='архив'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='musicians', to='demobaza.City', verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='musicians', to='demobaza.Genre', verbose_name='жанры'),
        ),
    ]
