# Generated by Django 2.1.4 on 2018-12-25 20:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('demobaza', '0007_auto_20181225_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('sort_ordering', models.SmallIntegerField(verbose_name='порядок сортировки')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='название')),
                ('duration_sec', models.PositiveIntegerField(editable=False, verbose_name='длина, сек.')),
                ('file', models.FileField(upload_to='tracks', verbose_name='.mp3')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='demobaza.Project')),
            ],
            options={
                'verbose_name': 'трек',
                'verbose_name_plural': 'треки',
                'ordering': ('sort_ordering',),
            },
        ),
        migrations.AddField(
            model_name='city',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='создан'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genre',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='создан'),
            preserve_default=False,
        ),
    ]
