# Generated by Django 2.1.4 on 2018-12-25 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demobaza', '0010_auto_20181225_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='demobaza.City', verbose_name='город'),
        ),
    ]
