# Generated by Django 2.1.4 on 2018-12-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demobaza', '0013_project_userpic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='userpic',
            field=models.ImageField(help_text='300x300px', upload_to='img/userpic', verbose_name='Аватарка проекта'),
        ),
    ]
