# Generated by Django 2.1.4 on 2018-12-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demobaza', '0014_auto_20181226_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='userpic',
            field=models.TextField(default='filipp.jpg'),
        ),
    ]
