# Generated by Django 2.1.4 on 2018-12-27 20:15

from django.db import migrations

def insert_genre(apps, schema_editor):
    Genre = apps.get_model("demobaza", "Genre")
    Genre.objects.create(name="Авторская песня", slug="автпесня")
    Genre.objects.create(name="Фолк", slug="фолк")
    Genre.objects.create(name="Этно", slug="этно")
    Genre.objects.create(name="Джаз", slug="джаз")
    Genre.objects.create(name="Блюз", slug="блюз")
    Genre.objects.create(name="Тяжелый рок", slug="тяжрок")

class Migration(migrations.Migration):

    dependencies = [
        ('demobaza', '0016_remove_project_userpic'),
    ]

    operations = [migrations.RunPython(insert_genre),
    ]